name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker/shaaban-vote
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - run: docker push docker.io/docker/shaaban-vote
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
            # Username used to log against the Docker registry
        username: ${{secrets.DOCKER_USER}}# optional
    # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_PASSWORD}}
   
